### ISSUE TITLE
absl.flags._exceptions.IllegalFlagValueError

### ISSUE THREAD

**Issue by yufanLIU** [Dejiao2018/GrOWL#2]
Thank you for sharing. I am interesed in your work and try to run the source code. However, when I ran 'python vgg_main.py ', I encounted the following errors:
Traceback (most recent call last):
  File "vgg_main.py", line 16, in <module>
    from flags import FLAGS
  File "/home/liuyufan/GrOWL/VGG/flags.py", line 113, in <module>
    flags.DEFINE_string('PLD_transition', 0.1, '[0,1]')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 107, in __init__
    self._set_default(default)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 196, in _set_default
    self.default = self._parse(value)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --PLD_transition=0.1: flag value must be a string, found "<type 'float'>"

Do you know how to fix this bug?  Thank you very much for your help.

**Comment by hammer-wang** [comment]
Can you try changing line 113 of flags.py to `flags.DEFINE_float('PLD_transition', 0.1, '[0,1]')`?

**Comment by yufanLIU** [comment]
It works!  Thanks very much!

**Comment by hammer-wang** [comment]
Closing issue.
